import FWCore.ParameterSet.Config as cms

_maxNumPart = 4096

PatSimonJetProducer = cms.EDProducer("PatSimonJetProducer",
    jetSrc = cms.InputTag("selectedPatJets"),
    EM0threshold = cms.double(-1.0),
    HAD0threshold = cms.double(-1.0),
    HADCHthreshold = cms.double(-1.0),
    ELEthreshold = cms.double(-1.0),
    MUthreshold = cms.double(-1.0),
    maxNumPart = cms.uint32(_maxNumPart),
    minNumPart = cms.uint32(2),
    verbose = cms.int32(1),
    minPt = cms.double(20),
    maxEta = cms.double(2.1),
    maxMuFrac = cms.double(0.8),
    maxChEmFrac = cms.double(0.8),
    eventSelection = cms.InputTag(""),
    doEventSelection = cms.bool(False),
    applyJEC=cms.bool(False),
    applyPuppi = cms.bool(True),
    rescaleMiniAODtruncation = cms.bool(False),
    CHSsrc = cms.InputTag(""),
    addCHSindex = cms.bool(False),
    CHSmatchDR = cms.double(0.2),
)

GenSimonJetProducer = cms.EDProducer("GenSimonJetProducer",
    jetSrc = cms.InputTag("ak4GenJetsNoNu"),
    EM0threshold = cms.double(-1.0),
    HAD0threshold = cms.double(-1.0),
    HADCHthreshold = cms.double(-1.0),
    ELEthreshold = cms.double(-1.0),
    MUthreshold = cms.double(-1.0),
    maxNumPart = cms.uint32(_maxNumPart),
    minNumPart = cms.uint32(0),
    verbose = cms.int32(1),
    minPt = cms.double(10),
    maxEta = cms.double(2.5),
    maxMuFrac = cms.double(999),
    maxChEmFrac = cms.double(999),
    eventSelection = cms.InputTag(""),
    doEventSelection = cms.bool(False),
    applyJEC=cms.bool(False),
    applyPuppi = cms.bool(False),
    rescaleMiniAODtruncation = cms.bool(False),
    CHSsrc = cms.InputTag(""),
    addCHSindex = cms.bool(False),
    CHSmatchDR = cms.double(0.4),
)
